
run1:
	g++ -std=c++17 -o build/1.leet 1.leet.cpp && ./build/1.leet

run2:
	g++ -std=c++17 -o build/2.leet 2.leet.cpp && ./build/2.leet

run3:
	g++ -std=c++17 -o build/3.leet 3.leet.cpp && ./build/3.leet

run4:
	g++ -std=c++17 -o build/4.leet 4.leet.cpp && ./build/4.leet

run5:
	g++ -std=c++17 -o build/5.leet 5.leet.cpp && ./build/5.leet

run6:
	g++ -std=c++17 -o build/6.leet 6.leet.cpp && ./build/6.leet

run7:
	g++ -std=c++17 -o build/7.leet 7.leet.cpp && ./build/7.leet

run8:
	g++ -std=c++17 -o build/8.leet 8.leet.cpp && ./build/8.leet

run9:
	g++ -std=c++17 -o build/9.leet 9.leet.cpp && ./build/9.leet

run10:
	g++ -std=c++17 -o build/10.leet 10.leet.cpp && ./build/10.leet

run11:
	g++ -std=c++17 -o build/11.leet 11.leet.cpp && ./build/11.leet

run12:
	g++ -std=c++17 -o build/12.leet 12.leet.cpp -g -Wall && ./build/12.leet

run12gdb: run12
	gdb ./build/12.leet

run13:
	g++ -std=c++17 -o build/13.leet 13.leet.cpp && ./build/13.leet

run14:
	g++ -std=c++17 -o build/14.leet 14.leet.cpp && ./build/14.leet

run15:
	g++ -std=c++17 -o build/15.leet 15.leet.cpp && ./build/15.leet

run16:
	g++ -std=c++17 -o build/16.leet 16.leet.cpp && ./build/16.leet

run17:
	g++ -std=c++17 -o build/17.leet 17.leet.cpp && ./build/17.leet

run18:
	g++ -std=c++17 -o build/18.leet 18.leet.cpp && ./build/18.leet

run19:
	g++ -std=c++17 -o build/19.leet 19.leet.cpp && ./build/19.leet

run20:
	g++ -std=c++17 -o build/20.leet 20.leet.cpp && ./build/20.leet

run21:
	g++ -std=c++17 -o build/21.leet 21.leet.cpp && ./build/21.leet

run22:
	g++ -std=c++17 -o build/22.leet 22.leet.cpp && ./build/22.leet


