
run1:
	g++ -std=c++17 -o build/1.leet 1.leet.cpp && ./build/1.leet

run2:
	g++ -std=c++17 -o build/2.leet 2.leet.cpp && ./build/2.leet

run3:
	g++ -std=c++17 -o build/3.leet 3.leet.cpp && ./build/3.leet

