
run1:
	g++ -std=c++17 -o build/1.leet 1.leet.cpp && ./build/1.leet

run2:
	g++ -std=c++17 -o build/2.leet 2.leet.cpp && ./build/2.leet

run3:
	g++ -std=c++17 -o build/3.leet 3.leet.cpp && ./build/3.leet

run4:
	g++ -std=c++17 -o build/4.leet 4.leet.cpp && ./build/4.leet

run5:
	g++ -std=c++17 -o build/5.leet 5.leet.cpp && ./build/5.leet

run6:
	g++ -std=c++17 -o build/6.leet 6.leet.cpp && ./build/6.leet

run7:
	g++ -std=c++17 -o build/7.leet 7.leet.cpp && ./build/7.leet

run8:
	g++ -std=c++17 -o build/8.leet 8.leet.cpp && ./build/8.leet

run9:
	g++ -std=c++17 -o build/9.leet 9.leet.cpp && ./build/9.leet

run10:
	g++ -std=c++17 -o build/10.leet 10.leet.cpp && ./build/10.leet

run11:
	g++ -std=c++17 -o build/11.leet 11.leet.cpp && ./build/11.leet

run12:
	g++ -std=c++17 -o build/12.leet 12.leet.cpp -g -Wall && ./build/12.leet

run12gdb: run12
	gdb ./build/12.leet