
run1:
	g++ -std=c++17 -o build/1.factory_method 1.factory_method.cpp && ./build/1.factory_method

run2:
	g++ -std=c++17 -o build/2.abstract_factory 2.abstract_factory.cpp && ./build/2.abstract_factory
