
run1:
	g++ -std=c++17 -o build/1.factory_method ./1.factory_method/1.factory_method.cpp && ./build/1.factory_method

run2:
	g++ -std=c++17 -o build/2.abstract_factory ./2.abstract_factory/2.abstract_factory.cpp && ./build/2.abstract_factory

run3:
	g++ -std=c++17 -o build/3.singleton ./3.singleton/3.singleton.cpp -pthread && ./build/3.singleton

run4:
	g++ -std=c++17 -o build/4.prototype ./4.prototype/4.prototype.cpp && ./build/4.prototype
