
run1:
	g++ -std=c++17 -o build/1.decorator ./1.decorator/1.decorator.cpp && ./build/1.decorator

run2:
	g++ -std=c++17 -o build/2.proxy ./2.proxy/2.proxy.cpp && ./build/2.proxy

run3:
	g++ -std=c++17 -o build/3.adapter ./3.adapter/3.adapter.cpp && ./build/3.adapter

run4:
	g++ -std=c++17 -o build/4.facade ./4.facade/4.facade.cpp && ./build/4.facade

run5:
	g++ -std=c++17 -o build/5.composite ./5.composite/5.composite.cpp && ./build/5.composite

run6:
	g++ -std=c++17 -o build/6.bridge ./6.bridge/6.bridge.cpp && ./build/6.bridge

run61:
	g++ -std=c++17 -o build/6.bridge_unique_ptr ./6.bridge/6.bridge_unique_ptr.cpp && ./build/6.bridge_unique_ptr

run7:
	g++ -std=c++17 -o build/7.flyweight ./7.flyweight/7.flyweight.cpp && ./build/7.flyweight
