
run1:
	g++ -std=c++17 -o build/1.decorator ./1.decorator/1.decorator.cpp && ./build/1.decorator

run2:
	g++ -std=c++17 -o build/2.proxy ./2.proxy/2.proxy.cpp && ./build/2.proxy

run3:
	g++ -std=c++17 -o build/3.adapter ./3.adapter/3.adapter.cpp && ./build/3.adapter

run4:
	g++ -std=c++17 -o build/4.facade ./4.facade/4.facade.cpp && ./build/4.facade

run5:
	g++ -std=c++17 -o build/5.composite ./5.composite/5.composite.cpp && ./build/5.composite
